- name: install haproxy
  hosts: k8s-lb
  become: true
  roles:
  - roles/haproxy

- name: install kubernetes cluster
  hosts: k8s-masters,k8s-workers
  become: true
  serial: 1
  roles:
  - roles/kubernetes

- name: ingress controller
  hosts: kubm1
  become: true
  roles:
  - addons
